# Site settings

baseurl: ""
theme: jekyll-theme-minimal

# Sass
sass:
  style: compressed


# Build settings
exclude: ["Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
