# Site settings

title: "Dafins Ramblings"
baseurl: ""

google_analytics: 

# Sass
sass:
  style: compressed


# Build settings
exclude: ["Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:title/

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
